# Generated by Django 5.0.4 on 2024-04-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('unique_selection', 'Unica seleccion'), ('selector', 'Selector'), ('open', 'Abierta')], max_length=64)),
                ('stage', models.IntegerField()),
            ],
        ),
    ]
