# Generated by Django 5.0.4 on 2024-04-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='title',
            new_name='answer',
        ),
    ]
